version: "3.7"

services:

  database:
    image: library/postgres:12.3
    env_file:
      - postgres/postgres-env.list
    volumes:
    - database-data:/var/lib/postgressql/data
    restart: always
    ports:
      - "5432:5432"
    secrets:
      - POSTGRES_PWD

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    env_file:
      - postgres/pgadmin-env.list
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    #links:
    #  - "db:bread-ai_server"
    secrets:
      - PGADMIN_PWD

  cron:
    image: docker-cron
    restart: always
    build: ./CRON
    volumes:
      - ./crontab:/var/spool/cron/crontabs/root
      - ./weather_data:/var/lib/docker/volumes/weather_data/_data

  flask:
    build: ./flask
    container_name: flask
    restart: always
    depends_on:
      - database
      - nginx
    environment:
      - APP_NAME=bread-ai
    ports:
    - "8081:8081"

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
    - "80:80"

secrets:
  POSTGRES_PWD:
    file: devsecrets/postgres_pwd
  PGADMIN_PWD:
    file: devsecrets/pgadmin_pwd

volumes:
  database-data:
  pgadmin-data:
