name: bread-ai_dev

channels:
- conda-forge
- defaults

dependencies:
 - python=3.7
 - numpy
 - scipy
 - pandas
 - seaborn
 - scikit-learn
 - jupyter
 - matplotlib
 - statsmodels
 - pylab
 - itertools
